name: geomesh-env
channels:
  - conda-forge
dependencies:
  - python=3.7.9
  - gdal=3.2.1
  - geos=3.9.1
  - proj=7.2.0
  - netcdf4=1.5.6
  - udunits2=2.2.27.27
  - pyproj=3
  - shapely=1.7.1
  - rasterio=1.2.4
  - fiona=1.8.18
  - pygeos=0.10
  - geopandas=0.9.0
  - utm=0.7.0
  - scipy=1.6.3
  - numpy=1.20.3
  - matplotlib=3.4.2
  - requests=2.25.1
  - tqdm=4.61.0
  - mpi4py=3.0.3
  - pyarrow=4.0.0
  - pytz=2021.1
  - geoalchemy2=0.6.3
  - jigsawpy=0.3.3
  - colored-traceback-0.3.0
