name: ocsmesh-env
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - gdal=3.3.2
  - geos=3.9.1
  - proj=8.1.1
  - netcdf4=1.5.7
  - udunits2=2.2.27.27
  - pyproj=3.2.1
  - shapely=1.7.1
  - rasterio=1.2.9
  - fiona=1.8.20
  - pygeos=0.10.2
  - geopandas=0.10.0
  - utm=0.7.0
  - scipy=1.7.1
  - numpy=1.21.2
  - matplotlib=3.4.3
  - requests=2.26.0
  - tqdm=4.62.3
  - mpi4py=3.1.1
  - pyarrow=5.0.0
  - pytz=2021.1
  - geoalchemy2=0.6.3
  - colored-traceback=0.3.0
