name: Pylint

on: [push]

jobs:
  format-check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Conda environment for Python
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9 # TODO: For testing use matrix of env
        environment-file: ./environment.yml
        activate-environment: ocsmesh-env
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        python ./setup.py install_jigsaw
        pip install .
    - name: Analysing the code with pylint
      shell: bash -l {0}
      run: |
        conda install -cconda-forge pylint=2.11.1 # For fail-on option
        pylint ocsmesh
